# Generated by Django 5.1.2 on 2024-12-03 17:07

import cleaning_app.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.JSONField(blank=True, default=cleaning_app.main.models.User.default_allergies, null=True),
        ),
    ]
