# Generated by Django 5.1.2 on 2024-12-04 21:59

import cleaning_app.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_allergies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='service_provider',
            name='preferred_rooms',
            field=models.JSONField(default=cleaning_app.main.models.Service_Provider.default_rooms),
        ),
    ]
