# Generated by Django 5.1.2 on 2024-10-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.ManyToManyField(related_name='job_tasks', to='main.task'),
        ),
    ]
