# Generated by Django 5.1.2 on 2024-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
