# Generated by Django 5.1.2 on 2024-10-31 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_jobs', to='main.job'),
        ),
    ]
