# Generated by Django 5.1.2 on 2024-10-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='service_provider_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
