# Generated by Django 5.1.2 on 2024-11-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_allergies'),
    ]

    operations = [
    ]
