# Generated by Django 5.1.2 on 2024-11-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_password'),
        ('main', '0007_alter_user_password'),
    ]

    operations = [
    ]
