# Generated by Django 5.1.2 on 2024-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20241121_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='pet_friendly',
            field=models.BooleanField(default=True),
        ),
    ]
