# Generated by Django 5.1.2 on 2024-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_remove_user_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_account',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='devicetoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='payment_method',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='job',
        ),
        migrations.RemoveField(
            model_name='task',
            name='room',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='default_home',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_made',
        ),
        migrations.RemoveField(
            model_name='job',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='job',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_name',
        ),
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.JSONField(blank=True, choices=[('none', 'None'), ('dogs', 'Dogs'), ('cats', 'Cats'), ('dust', 'Dust'), ('pollen', 'Pollen'), ('mold', 'Mold'), ('fragrance', 'Fragrance'), ('SLS', 'SLS'), ('ammonia', 'Ammonia'), ('bleach', 'Bleach'), ('other', 'Other')], default='none', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Bank_Account',
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Payment_Method',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
